
#Analytics Service Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: analytics-service
  name: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - image: bhavya612/grades-application-docker-analytics-service:latest
          name: analytics-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "100m"
      restartPolicy: Always

---
#Auth service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - image: bhavya612/grades-application-docker-auth-service:latest
          name: auth-service
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

---
#Enter-Data service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enter-data-service
  template:
    metadata:
      labels:
        app: enter-data-service
    spec:
      containers:
        - name: enter-data-service
          image: bhavya612/grades-application-docker-enter-data-service:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm1
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm1
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
          ports:
            - containerPort: 5001

---
#MongoDB service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-db
  name: mongo-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"

          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
---
#MySQL service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: grades_db
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
          image: mysql:5.7

          name: mysql
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"

          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-service
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: mysql-cm1
              subPath: init.sql
      restartPolicy: Always
      volumes:
        - name: mysql-service
          persistentVolumeClaim:
            claimName: mysql-service
        - configMap:
            items:
              - key: init.sql
                path: init.sql
            name: mysql-cm1
          name: mysql-cm1
---
#Show-Results Service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: show-results
  name: show-results
spec:
  replicas: 3
  selector:
    matchLabels:
      app: show-results
  template:
    metadata:
      labels:
        app: show-results
    spec:
      containers:
        - image: bhavya612/grades-application-docker-show-results:latest
          name: show-results
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
