version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
 
  enter-data-service:
    build: ./enter-data-service
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql  
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: grades_db
    networks:
      - app-network

  mongo-db:
      image: mongo:latest
      container_name: mongo
      volumes:
        - ./mongo_data:/data/db
      ports:
        - "27017:27017"
      networks:
        - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grades_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-service/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  analytics-service:
    build: ./analytics-service
    depends_on:
      - mysql
      - mongo-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
