apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded: password
  MYSQL_USER: dXNlcg==              # Base64 encoded: user
  MYSQL_PASSWORD: cGFzc3dvcmQ=      # Base64 encoded: password
  DB_NAME: Z3JhZGVzX2Ri             # Base64 encoded: grades_db
